package pl.polsl.lab.servlets.search;

import java.io.*;
import java.util.Date;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.*;

/**
 * Main class of the servlet displaying current time, date and image. Site
 * generated by servlet is refreshed every 10 seconds.
 *
 * @author Gall Anonim
 * @version 1.0
 */
@WebServlet("/Search")
public class SearchServlet extends HttpServlet {

    
     /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }
    
    
     /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    public void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        response.setContentType("text/html; charset=ISO-8859-2");
        PrintWriter out = response.getWriter();
        
        var html = "<form action=\"SearchResponse\" method=\"GET\">\n" +
            "<select name=\"Type\">\n" +
            "  <option value=\"ID\">ID</option>\n" +
            "  <option value=\"Title\">Title</option>\n" +
            "  <option value=\"Author\">Author</option>\n" +
            "</select>" +
            "<input type=text size=20 name=\"input\">\n" +
            "<input type=\"submit\" value=\"Search\" />\n" +
            "</form>";
        
        out.println("<html>\n<body style=\"background-color:#B1D0E0;\"><center><br><br><br>\n" + html + "\n</center></body>\n</html>");
    }
}
